# Generated by Django 2.0.6 on 2018-06-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('blog', '0008_auto_20180623_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='BlogAuthor',
        ),
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name_plural': 'blog authors'},
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='categories',
            new_name='author',
        ),
    ]
    atomic = False
