# Generated by Django 2.0.6 on 2018-06-24 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0010_genericpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericPage',
            new_name='AboutPage',
        ),
    ]
