# Generated by Django 2.0.6 on 2018-06-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='headshot',
        ),
    ]
