# Generated by Django 2.0.6 on 2018-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180626_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='gig_date',
            field=models.DateField(default='01-01-1066', verbose_name='gig_date'),
        ),
    ]
    atomic = False
