# Generated by Django 2.0.6 on 2018-06-26 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180626_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='gig_location',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='gig_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 26, 10, 57, 40, 909857, tzinfo=utc)),
        ),
    ]
