# Generated by Django 2.0.6 on 2018-06-26 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180626_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='gig_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 26, 11, 5, 0, 270456, tzinfo=utc)),
        ),
    ]
