# Generated by Django 2.0.6 on 2018-06-26 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('blog', '0026_auto_20180626_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='representative_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='gig_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 26, 12, 9, 52, 382291, tzinfo=utc)),
        ),
    ]
