# Generated by Django 2.0.6 on 2018-06-26 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20180626_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='gig_time',
            field=models.CharField(default="19:30", max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='gig_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
    atomic=False
