# Generated by Django 2.0.6 on 2018-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20180626_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='gig_time',
            field=models.CharField(default='19:30', max_length=5),
        ),
    ]
    atomic=False
