# Generated by Django 2.0.6 on 2018-06-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_blogpage_representative_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
    atomic=False
