# Generated by Django 2.0.6 on 2018-06-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180627_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={},
        ),
    ]
