# Generated by Django 2.0.6 on 2018-06-28 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('blog', '0036_bloghistoricindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogHistoricIndexPage',
            new_name='BlogArchives',
        ),
    ]
    atomic=False
