# Generated by Django 2.0.6 on 2018-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20180628_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location_link',
            field=models.CharField(default='www.uptheantics.co.uk', max_length=2083),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='price',
            field=models.CharField(default='5', max_length=6),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='ticket_link',
            field=models.CharField(default='www.uptheantics.co.uk', max_length=2083),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='gig_location',
            field=models.CharField(default='Location TBA', max_length=200),
        ),
    ]
