# Generated by Django 2.0.6 on 2018-07-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0039_auto_20180703_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
